motors:
  Camera: {acceleration: 255, assembly: bodyNC, default: 0, group: Neck, hardware: feetech,
    init: 2150, labelleft: Camera, max: 0.8436894333371027, min: -0.6902913545485385,
    motor_id: 53, motor_max: 2700, motor_min: 1700, name: Camera, protocol: 0, sort_no: 104,
    speed: 0, topic: feetechTorso, transmission: 0.01}
  LeftElbowPitch:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: LeftArm
    hardware: feetech
    init: 3549
    labelleft: LeftElbowPitch
    max: 0.0015339807878856412
    min: -0.0015339807878856412
    motor_id: 83
    motor_max: 3550
    motor_min: 3548
    name: LeftElbowPitch
    pau:
      function:
      - {name: linear, scale: -0.0349, translate: 2.06}
      parser: {joint: L_Elbow, name: armsangles}
    protocol: 0
    sort_no: -76
    speed: 100
    topic: feetechLarm
    transmission: 1
  LeftElbowYaw:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: LeftArm
    hardware: feetech
    init: 950
    labelleft: LeftElbowYaw
    max: 0.04601942363656923
    min: -0.23009711818284617
    motor_id: 84
    motor_max: 980
    motor_min: 800
    name: LeftElbowYaw
    pau:
      function:
      - {name: linear, scale: 0.0157, translate: 0}
      parser: {joint: L_Wrist_Yaw, name: armsangles}
    protocol: 1
    sort_no: -75
    speed: 100
    topic: feetechLarm
    transmission: 1
  LeftShoulderPitch:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: LeftArm
    hardware: feetech
    init: 1001
    labelleft: LeftShoulderPitch
    max: 0.0015339807878856412
    min: -0.0015339807878856412
    motor_id: 80
    motor_max: 1002
    motor_min: 1000
    name: LeftShoulderPitch
    pau:
      function:
      - {name: linear, scale: -0.0272, translate: 0}
      parser: {joint: L_Shoulder_Pitch, name: armsangles}
    protocol: 0
    sort_no: -79
    speed: 100
    topic: feetechLarm
    transmission: 0.01
  LeftShoulderRoll:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: LeftArm
    hardware: feetech
    init: 2800
    labelleft: LeftShoulderRoll
    max: 0.07669903939428206
    min: -0.30679615757712825
    motor_id: 81
    motor_max: 2850
    motor_min: 2600
    name: LeftShoulderRoll
    pau:
      function:
      - {name: linear, scale: 0.0349, translate: 0}
      parser: {joint: L_Shoulder_Roll, name: armsangles}
    protocol: 0
    sort_no: -78
    speed: 100
    topic: feetechLarm
    transmission: 1
  LeftShoulderYaw:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: LeftArm
    hardware: feetech
    init: 2750
    labelleft: LeftShoulderYaw
    max: 0.07669903939428206
    min: -0.23009711818284617
    motor_id: 82
    motor_max: 2800
    motor_min: 2600
    name: LeftShoulderYaw
    pau:
      function:
      - {name: linear, scale: -0.0504, translate: 0}
      parser: {joint: L_Shoulder_Yaw, name: armsangles}
    protocol: 0
    sort_no: -77
    speed: 100
    topic: feetechLarm
    transmission: 1
  LowerGimbalLeft:
    acceleration: 100
    assembly: bodyNC
    default: 0
    group: Neck
    hardware: feetech
    init: 2130
    labelleft: LowerGimbalLeft
    max: 1.3345632854605078
    min: -0.3528155812136975
    motor_id: 51
    motor_max: 3000
    motor_min: 1900
    name: LowerGimbalLeft
    pau:
      function:
      - {axis: loright, name: quaternion2dual}
      - {name: linear, scale: -1, translate: 0}
      parser: {name: getproperty, property: m_neckRotation}
    protocol: 0
    sort_no: 101
    speed: 500
    topic: feetechTorso
    transmission: 1
  LowerGimbalRight:
    acceleration: 100
    assembly: bodyNC
    default: 0
    group: Neck
    hardware: feetech
    init: 2070
    labelleft: LowerGimbalRight
    max: 0.3528155812136975
    min: -1.3345632854605078
    motor_id: 52
    motor_max: 2300
    motor_min: 1200
    name: LowerGimbalRight
    pau:
      function:
      - {axis: loleft, name: quaternion2dual}
      - {name: linear, scale: -1, translate: 0}
      parser: {name: getproperty, property: m_neckRotation}
    protocol: 0
    sort_no: 102
    speed: 500
    topic: feetechTorso
    transmission: 1
  NeckRotation:
    acceleration: 255
    assembly: bodyNC
    default: 0
    group: Neck
    hardware: feetech
    init: 2000
    labelleft: NeckRotation
    max: 0.6135923151542565
    min: -0.6135923151542565
    motor_id: 50
    motor_max: 2400
    motor_min: 1600
    name: NeckRotation
    pau:
      function:
      - {axis: z, name: quaternion2euler}
      - {name: linear, scale: 1, translate: 0}
      parser: {name: getproperty, property: m_headRotation}
    protocol: 0
    sort_no: 103
    speed: 0
    topic: feetechTorso
    transmission: 1
  RightElbowPitch:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 2200
    labelleft: RightElbowPitch
    max: 2.0708740636456158
    min: -2.1475731030398975
    motor_id: 63
    motor_max: 3550
    motor_min: 800
    name: RightElbowPitch
    pau:
      function:
      - {name: linear, scale: 0.0349, translate: -2.06}
      parser: {joint: R_Elbow, name: armsangles}
    protocol: 0
    sort_no: -96
    speed: 100
    topic: feetechRarm
    transmission: 1
  RightElbowYaw:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 495
    labelleft: RightElbowYaw
    max: 0.7439806821245359
    min: -0.6826214506091103
    motor_id: 64
    motor_max: 980
    motor_min: 50
    name: RightElbowYaw
    pau:
      function:
      - {name: linear, scale: 0.0157, translate: 0}
      parser: {joint: R_Wrist_Yaw, name: armsangles}
    protocol: 1
    sort_no: -95
    speed: 100
    topic: feetechRarm
    transmission: 1
  RightFingerSpread:
    acceleration: 1
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: pololu
    init: 1057
    labelleft: RightFingerSpread
    max: 1.3880638681968325
    min: -0.18273245859806403
    motor_id: 14
    motor_max: 1847
    motor_min: 953
    name: RightFingerSpread
    pau:
      function:
      - {max: 40, min: -8, name: linear}
      parser: {joint: R_Spreading, name: armsangles}
    protocol: 0
    sort_no: -81
    speed: 0
    topic: rhand
    transmission: 1
  RightIndexFinger:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 2900
    labelleft: RightIndexFinger
    max: 0.30679615757712825
    min: -2.9145634969827183
    motor_id: 69
    motor_max: 3100
    motor_min: 1000
    name: RightIndexFinger
    pau:
      function:
      - {max: -10, min: 40, name: linear}
      parser: {joint: R_Index_Finger, name: armsangles}
    protocol: 0
    sort_no: -85
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightMiddleFinger:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 1550
    labelleft: RightMiddleFinger
    max: 2.9912625363770005
    min: -0.6902913545485385
    motor_id: 70
    motor_max: 3500
    motor_min: 1100
    name: RightMiddleFinger
    pau:
      function:
      - {max: -40, min: 10, name: linear}
      parser: {joint: R_Middle_Finger, name: armsangles}
    protocol: 0
    sort_no: -84
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightPinkyFinger:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 2040
    labelleft: RightPinkyFinger
    max: 0.3988350048502667
    min: -1.748738098189631
    motor_id: 72
    motor_max: 2300
    motor_min: 900
    name: RightPinkyFinger
    pau:
      function:
      - {max: 10, min: -40, name: linear}
      parser: {joint: R_Pinky_Finger, name: armsangles}
    protocol: 0
    sort_no: -82
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightRingFinger:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 1600
    labelleft: RightRingFinger
    max: 3.067961575771282
    min: -0.46019423636569234
    motor_id: 71
    motor_max: 3600
    motor_min: 1300
    name: RightRingFinger
    pau:
      function:
      - {max: -40, min: 10, name: linear}
      parser: {joint: R_Ring_Finger, name: armsangles}
    protocol: 0
    sort_no: -83
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightShoulderPitch:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 2900
    labelleft: RightShoulderPitch
    max: 0.9203884727313847
    min: -2.9145634969827183
    motor_id: 60
    motor_max: 3500
    motor_min: 1000
    name: RightShoulderPitch
    pau:
      function:
      - {name: linear, scale: 0.0272, translate: 0}
      parser: {joint: R_Shoulder_Pitch, name: armsangles}
    protocol: 0
    sort_no: -99
    speed: 100
    topic: feetechRarm
    transmission: 1
  RightShoulderRoll:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 1100
    labelleft: RightShoulderRoll
    max: 2.60776733940559
    min: -0.07669903939428206
    motor_id: 61
    motor_max: 2800
    motor_min: 1050
    name: RightShoulderRoll
    pau:
      function:
      - {name: linear, scale: 0.0349, translate: 0}
      parser: {joint: R_Shoulder_Roll, name: armsangles}
    protocol: 0
    sort_no: -98
    speed: 100
    topic: feetechRarm
    transmission: 0.01
  RightShoulderYaw:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 1700
    labelleft: RightShoulderYaw
    max: 2.60776733940559
    min: -1.6873788666742053
    motor_id: 62
    motor_max: 3400
    motor_min: 600
    name: RightShoulderYaw
    pau:
      function:
      - {name: linear, scale: -0.0504, translate: 0}
      parser: {joint: R_Shoulder_Yaw, name: armsangles}
    protocol: 0
    sort_no: -97
    speed: 100
    topic: feetechRarm
    transmission: 1
  RightThumbFinger:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 2450
    labelleft: RightThumbFinger
    max: 0.38349519697141027
    min: -2.2242721424341796
    motor_id: 68
    motor_max: 2700
    motor_min: 1000
    name: RightThumbFinger
    pau:
      function:
      - {max: -20, min: 40, name: linear}
      parser: {joint: R_Thumb_Finger, name: armsangles}
    protocol: 0
    sort_no: -87
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightThumbRoll:
    acceleration: 25
    assembly: bodyNC
    default: 0
    group: RightHand
    hardware: feetech
    init: 2460
    labelleft: RightThumbRoll
    max: 0.5982525072754
    min: -0.705631162427395
    motor_id: 67
    motor_max: 2850
    motor_min: 2000
    name: RightThumbRoll
    pau:
      function:
      - {max: -20, min: 40, name: linear}
      parser: {joint: R_Thumb_Roll, name: armsangles}
    protocol: 0
    sort_no: -88
    speed: 0
    topic: feetechRarm
    transmission: 1
  RightWristPitch:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 1965
    labelleft: RightWristPitch
    max: 0.0015339807878856412
    min: -0.0015339807878856412
    motor_id: 65
    motor_max: 1966
    motor_min: 1964
    name: RightWristPitch
    pau:
      function:
      - {max: 40, min: -40, name: linear}
      parser: {joint: R_Wrist_Pitch, name: armsangles}
    protocol: 0
    sort_no: -90
    speed: 100
    topic: feetechRarm
    transmission: 1
  RightWristRoll:
    acceleration: 15
    assembly: bodyNC
    default: 0
    group: RightArm
    hardware: feetech
    init: 2042
    labelleft: RightWristRoll
    max: 0.0015339807878856412
    min: -0.0015339807878856412
    motor_id: 66
    motor_max: 2043
    motor_min: 2041
    name: RightWristRoll
    pau:
      function:
      - {max: -40, min: 40, name: linear}
      parser: {joint: R_Wrist_Pitch, name: armsangles}
    protocol: 0
    sort_no: -89
    speed: 100
    topic: feetechRarm
    transmission: 1
